pipeline{
    agent{
        label 'DevServer'
    }
    tools{
        maven 'maven'
    }
    parameters{
            choice choices: ['dev', 'prod'], name: 'select_env'
    }
    environment{
            NAME = "Saurabh"
    }
    
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package -DskipTests=true'
            }
        }
        stage('test'){
            parallel{
                stage('testA'){
                    agent {label 'DevServer'}
                    steps{
                        echo "This is testA"
                        sh "mvn test"
                    }
                }
                stage('testB'){
                    agent {label 'DevServer'}
                    steps{
                        echo "This is testB"
                        sh "mvn test"
                    }
                }
            }
            post{
               success {
                    '''archiveArtifacts artifacts: '**/target/*.jar'''
                    dir("target/"){
                        stash name: "maven-build", includes: "*.jar"
                    }
               }
            }
        }
        stage('deploy_dev'){
            when {expression {params.select_env == dev} beforeAgent true}
            agent{label 'DevServer'}
            steps{
                dir("/home/ubuntu/"){
                    unstash "maven-build"
                }
                sh """
                cd /home/ubuntu/
                java -jar my-app-1.0-SNAPSHOT.jar
                """ 
            }
        }
    }
}
