pipeline{
    agent{
        label 'DevServer'
    }
    tools{
        maven 'maven'
    }
    parameters{
            string defaultValue: 'Joseph', name: 'LASTNAME'
    }
    environment{
            NAME = "Saurabh"
    }
    
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package'
                echo "Hello $NAME ${params.LASTNAME}"
            }
        }
        stage('test'){
            parallel{
                stage('testA'){
                    steps{
                        echo "This is testA"
                    }
                }
                stage('testB'){
                    steps{
                        echo "This is testB"
                    }
                }
            }
            post{
               success {
                    archiveArtifacts artifacts: '**/target/*.jar'
               }
            }
        }
    }
}
